### ISSUE TITLE
now(tz) returns wrong value when using tz_offset

### ISSUE THREAD

**Issue by kaztai** [spulec/freezegun#179] opened 2017-04-08 05:12 UTC
freezegun 0.3.8

```
from freezegun import freeze_time
from datetime import datetime
import pytz, unittest
UTC = pytz.utc
JST = pytz.timezone('Asia/Tokyo')

class FeezeTimeTests(unittest.TestCase):
    def test_nooffset(self):
        with freeze_time("2017-01-01 00:00:00"):
            self.assertEqual(datetime.now(), datetime(2017,1,1,0,0,0))
            self.assertEqual(datetime.now(JST), datetime(2017,1,1,9,0,0,0,JST))
            self.assertEqual(datetime.now(UTC), datetime(2017,1,1,0,0,0,0,UTC))
            self.assertEqual(datetime.utcnow(), datetime(2017,1,1,0,0,0))

    def test_offset(self):
        with freeze_time("2017-01-01 00:00:00", tz_offset=9):
            self.assertEqual(datetime.now(), datetime(2017,1,1,9,0,0))
            self.assertEqual(datetime.now(JST), datetime(2017,1,1,9,0,0,0,JST))
            # AssertionError: FakeDatetime(2017, 1, 1, 18, 0, tzinfo=<DstTzInfo 'Asia/Tokyo' JST+9:00:00 STD>) != FakeDatetime(2017, 1, 1, 9, 0, tzinfo=<DstTzInfo 'Asia/Tokyo' JST+9:00:00 STD>)
            self.assertEqual(datetime.now(UTC), datetime(2017,1,1,0,0,0,0,UTC))
            # AssertionError: FakeDatetime(2017, 1, 1, 9, 0, tzinfo=<UTC>) != FakeDatetime(2017, 1, 1, 0, 0, tzinfo=<UTC>)
            self.assertEqual(datetime.utcnow(), datetime(2017,1,1,0,0,0))
```

**Comment by spulec** [comment] 2017-04-13 01:54
I'm a bit confused. In the `test_offset`, you are now passing a `tz_offset`, but only changing the first assertion.

**Comment by kaztai** [comment] 2017-05-21 04:12
Thank you for your response.
For the above sample,
`test_nooffset` is when tz_offset is not specified.
`test_offset` is when tz_offset is specified.
AssertionError will occur in two places when you run the test.
`Freeze_time ("2017-01-01 00:00:00", tz_offset = 9)`
When writing, I understand that the time string is UTC and that the time zone of local time is +9:00.
In that case, `datetime.now()` and `datetime.now(JST)` should be equal.
And `datetime.now(UTC)` and `datetime.utcnow()` should always be equal.
However, the results of the test are different.

**Comment by spulec** [comment] 2017-06-15 00:22
Is this the same as #89?

**Comment by spulec** [comment] 2018-03-06 02:03
Going to close as a dupe of #89. Let me know if that is wrong.

**Closed by spulec** 2018-03-06 02:03 UTC
