### ISSUE TITLE
Hangs in multiprocessing

### ISSUE THREAD

**Issue by devang-kredx** [spulec/freezegun#230] opened 2018-02-17 17:29 UTC
This test case hangs in Django 2.0 (works without freeze_time)-

```
from multiprocessing import Pool

from freezegun import freeze_time
from django.test import TestCase


@freeze_time("2018-02-14 11:00:00")
class MultiProcessingTestCase(TestCase):
    """
    Test case to test if pool process of multiprocessing works
    """
    def test_multi_processing(self):
        print("POOLING")
        with Pool(processes=2) as pool:
            pass
        print("DONE")
```

**Comment by spulec** [comment] 2018-03-06 02:37
Closing in favor of https://github.com/spulec/freezegun/issues/202

**Closed by spulec** 2018-03-06 02:37 UTC

**Comment by ods** [comment] 2018-10-18 17:49
> Can you supply a minimal test case?

Sure. But my case is not related to django. The following code hangs when executed as is, but works fine without `with freeze_time()` and with the hack I've described above: 

```
import asyncio
from concurrent.futures import ProcessPoolExecutor

from freezegun import freeze_time

executor = ProcessPoolExecutor()

def sync_func():
    pass

async def main():
    loop = asyncio.get_event_loop()
    with freeze_time():
        await loop.run_in_executor(executor, sync_func)

asyncio.run(main())
```

**Comment by LionelB5** [comment] 2021-05-09 07:13
I'm seeing similar behaviour after upgrading `freezegun` from `1.0.0` to `1.1.0`.

This minimal code snippet reproduces the issue:
```python
from multiprocessing import Pool
# using Pool from `multiprocessing.dummy` also results in a hang 
# from multiprocessing.dummy import Pool

from freezegun import freeze_time


@freeze_time('2020-01-01 00:00:00')
def reproduce_freezegun_hang():
    pool = Pool()
    pool.close()
    pool.join()  # hangs indefinitely here


if __name__ == '__main__':
    reproduce_freezegun_hang()
```

If I downgrade `freezegun` from `1.1.0` to `1.0.0` the hang does not happen.
Using the workaround mentioned by boxed in [this comment](https://github.com/spulec/freezegun/issues/230#issuecomment-430735777) solves the issue. Another workaround is to supply `tick=True` to `freeze_time`.

I am using Python `3.9.1`.

**Contents of `requirements.txt`**:
```
freezegun==1.1.0
    # via -r requirements.in
python-dateutil==2.8.1
    # via freezegun
six==1.16.0
    # via python-dateutil
```

**Comment by AaronDMarasco** [comment] 2022-04-14 21:44
I got it to stop hanging on `join()` with `extend_ignore_list` and adding `multiprocessing` to that. Sadly, that means that since my UUT is in another process from the test bench, applying the `tick()` doesn't affect the copy that got spun off, so looks like I can't use `freezegun` for this right now. 

I suspect this is also the cause of #359 - unless `freezegun` implements some kind of multiprocessing manager/namespace to share its state between processes, it's not gonna work. That's what my workaround was, but then I had to add the hooks to my class to explicitly call my time synchronization object, which sucks.

**Comment by snnbotchway** [comment] 2023-07-04 11:35
I set tick=True like so `@freeze_time("2023-06-27 14:30:00", tick=True)`

**Comment by ross-spencer** [comment] 2024-12-17 20:40
Tried LionelB5's test in light of some issues I am seeing in: https://github.com/spulec/freezegun/issues/359

```python
"""Recreating hang test."""

from multiprocessing import Pool

from freezegun import freeze_time


@freeze_time("2020-01-01 00:00:00")
def reproduce_freezegun_hang():
    print("recreating test here")
    pool = Pool()
    pool.close()
    pool.join()  # hangs indefinitely here
    print("out of hang")


if __name__ == "__main__":
    reproduce_freezegun_hang()
```

Freezegun: `freezegun==1.5.1`

Output:

```sh
$ time python hang_test.py
recreating test here
out of hang

real	0m0.130s
user	0m0.110s
sys	0m0.042s

```

The code seems to run fine in Ubuntu. @LionelB5 were you using MacOS at all?

**Comment by LionelB5** [comment] 2024-12-17 23:49
> Tried LionelB5's test in light of some issues I am seeing in: #359
> ...
> The code seems to run fine in Ubuntu. @LionelB5 were you using MacOS at all?

Hey @ross-spencer - At the time I was using Ubuntu.

I tried reproducing the problem using freezegun 1.1.0 and Python 3.9.1 and was able to. However, if I upgrade to 1.5.1 the code runs fine and does not hang.

Hope that helps narrow things down :+1:

**Comment by ross-spencer** [comment] 2024-12-18 11:13
Thanks @LionelB5 that should help make #359 more specific. I appreciate it!
