### ISSUE TITLE
freezetime breaks datetime.datetime.fromtimestamp(time.time())

### ISSUE THREAD

**Issue by kkpattern** [spulec/freezegun#153] opened 2016-09-09 09:38 UTC
`datetime.datetime.today()` should be equivalent to `datetime.fromtimestamp(time.time())`. However in 0.3.7 I get this result:

```
>>> import datetime
>>> import time
>>> from freezegun import freeze_time
>>> with freeze_time(datetime.datetime(2016, 9, 9)):
...     print datetime.datetime.today()
...     print datetime.datetime.fromtimestamp(time.time())
... 
2016-09-09 00:00:00
2016-09-09 08:00:00
```

It should be:

```
>>> import datetime
>>> import time
>>> print datetime.datetime.today(), datetime.datetime.fromtimestamp(time.time())
2016-09-09 17:36:33.659690 2016-09-09 17:36:33.659747
>>> 
```

It looks like something wrong with the time zone.

**Comment by spulec** [comment] 2017-01-19 04:04
Thanks for opening.

I believe this is a dupe of https://github.com/spulec/freezegun/issues/89. A solution is at https://github.com/spulec/freezegun/pull/136, but it hasn't been merged in yet.

I'm going to close, but feel free to reopen if you think my assessment is wrong.

**Closed by spulec** 2017-01-19 04:04 UTC
