### ISSUE TITLE
All frozen datetimes timezone-naive

### ISSUE THREAD

**Issue by majackson** [spulec/freezegun#218] opened 2017-12-21 12:14 UTC
I've been investigating some unittest warnings I'm getting from a django project which is complaining that a timezone-naive datetime is being inserted into a timezone-aware database column. I've tried resolving this by ensuring that my `freeze_time` argument is explicitly including timezone data in a way that `dateutil.parser.parse` recognises. However, it looks like freezegun will strip out any provided timezone data in [this function](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L225).

Investigating why this is the case led me to [this PR from 2014](https://github.com/spulec/freezegun/issues/48), in which a user has a problem passing a timezone-aware frozen datetime into a function which doesn't expect a timezone-aware datetime object. For some reason, the accepted resolution of this problem was to conclude that all frozen datetimes should be timezone-naive.

This seems very clearly like the wrong solution. If I explicitly specify a frozen time including timezone data, obviously I want that timezone data to be preserved. If I don't want timezone data, it's very straightforward to specify a `freeze_time` argument that will result in a timezone-naive datetime.

**Comment by spulec** [comment] 2018-03-06 02:24
Going to close this as a dupe of https://github.com/spulec/freezegun/issues/191

**Closed by spulec** 2018-03-06 02:24 UTC
