### ISSUE TITLE
1.2.2: missimg git tag

### ISSUE THREAD

**Issue by kloczek** [spulec/freezegun#490] opened 2023-02-15 14:06 UTC
https://pypi.org/project/freezegun/ shows that latest version is 1.2.2 however here there is no git tag for that version.
My automation is using git tags.
Is it possible to add missing git tag? .. please 🤔

**Comment by boxed** [comment] 2023-02-15 14:12
Duplicate of #468

**Comment by boxed** [comment] 2023-02-15 14:12
I would in general recommend you to move to time-machine.

**Closed by boxed** 2023-02-15 14:12 UTC

**Comment by kloczek** [comment] 2023-02-15 19:34
> I would in general recommend you to move to time-machine.

Hmm .. what you mean? 🤔

**Comment by boxed** [comment] 2023-02-15 19:36
https://github.com/adamchainz/time-machine is better than freezegun in every way I believe.
