### ISSUE TITLE
UTC datetime timestamp not correct

### ISSUE THREAD

**Issue by bitdivision** [spulec/freezegun#181] opened 2017-05-11 14:24 UTC
Python 3

Code:

```
import datetime
from freezegun import freeze_time

freezer_ts = 1400000000
freezer_time = datetime.datetime.utcfromtimestamp(freezer_ts)
freezer_string = freezer_time.isoformat()
print(freezer_string)

with freeze_time(freezer_string):
    print(datetime.datetime.utcnow().timestamp())
    print(datetime.datetime.utcnow())
```

Output:

```
2014-05-13T16:53:20
1399996400.0
2014-05-13 16:53:20
```

Expected:

```
2014-05-13T16:53:20
140000000.0
2014-05-13 16:53:20
```

The datetime object seems correct but the timestamp is not?

**Comment by spulec** [comment] 2017-05-13 00:22
I believe this is a duplicate of https://github.com/spulec/freezegun/issues/89

Let me know if you don't think that is the case.

**Closed by spulec** 2017-05-13 00:22 UTC

**Comment by kyrias** [comment] 2019-09-26 19:58
@spulec While it might be the same cause, I don't think it's really the same *issue*.

Let's say you do `freeze_time("2019-01-30T12:00:00+00:00")`.  I think it's entirely reasonable to then get `FakeDatetime(2019, 1, 30, 12, 0)` when calling both `now()` and `utcnow()`, which is what that issue is complaining about.

The problem here is that when my computer is in UTC+1, calling `utcnow().timestamp()` will get you the `1548846000.0`, which is actually the timestamp for `2019-01-30T11:00:00+00:00:00`, meaning that the timestamp generated is an hour off from what it should be.

Meanwhile `datetime.utcfromtimestamp(datetime.utcnow().timestamp())` will actually give you `FakeDatetime(2019, 1, 30, 11, 0)` as it should.

This means that `datetime.utcnow()` is **NOT** equal to `datetime.utcfromtimestamp(datetime.utcnow().timestamp())`, which is rather broken behaviour.
