### ISSUE TITLE
Version 0.3.15 has issue with dateutil.tz

### ISSUE THREAD

**Issue by markelrod** [spulec/freezegun#334] opened 2020-02-18 05:35 UTC
Upgraded to 0.3.15 from 0.3.14 and tests started to fail with:

`ImportError: Failed to import test module: api.tests.test_retry
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/Users/elrod/Development/python/django/redfive/api/tests/test_retry.py", line 7, in <module>
    from freezegun import freeze_time
  File "/Users/elrod/.local/share/virtualenvs/redfive-aKi7FZVD/lib/python3.7/site-packages/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/Users/elrod/.local/share/virtualenvs/redfive-aKi7FZVD/lib/python3.7/site-packages/freezegun/api.py", line 26, in <module>
    _EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.UTC)
AttributeError: module 'dateutil.tz' has no attribute 'UTC'`

reverting to 0.3.14 fixes issue.

**Comment by tladyman** [comment] 2020-02-18 10:14
This happens to me too. I had an old version of `python-dateutil`. It works with  more up to date version. 

Maybe freezegun should set a `>=` dependency on dateutil

**Comment by katyukha** [comment] 2020-02-18 16:29
Same issue.

Please, update version on PyPI as soon as possible.

Thanks)

**Comment by spulec** [comment] 2020-02-19 00:54
Going to close this as a dupe of https://github.com/spulec/freezegun/issues/333

**Closed by spulec** 2020-02-19 00:54 UTC
