### ISSUE TITLE
freezegun doesn't take timezones into account in some cases

### ISSUE THREAD

**Issue by WoLpH** [spulec/freezegun#309] opened 2019-09-19 03:39 UTC
Simple testcase:
```python
import time
import datetime

from freezegun import freeze_time


def test():
    a = time.mktime(datetime.datetime.now().timetuple())
    b = time.time()
    print(int(b - a))


with freeze_time():
    print('With freezegun:')
    test()


print('Without freezegun:')
test()
```

Results for me (I'm in GMT+2):
```
With freezegun:
7200
Without freezegun:
0
```

**Comment by WoLpH** [comment] 2019-09-19 04:13
A workaround for the issue:
```python
   # The timezone offset in seconds, add 10 seconds to make sure we don't
    # accidently get the wrong hour
    offset_seconds = (datetime.now() - datetime.utcnow()).seconds + 10
    offset_hours = int(offset_seconds / 3600)

    freeze_time = freezegun.freeze_time(tz_offset=offset_hours)
```

**Comment by spulec** [comment] 2019-09-24 03:19
By default, freezegun will freeze to the UTC time instead of the system's timezone so I think this is expected behavior.

I believe this issue is a dupe of https://github.com/spulec/freezegun/issues/89, but let me know if you don't think that is the case.

**Comment by WoLpH** [comment] 2019-09-24 09:51
I believe it's similar but different. That issue could also fix this issue, but for now the biggest problem is the inconsistency that some methods do and others do not take the timezone into account.

The issue is that if I replace datetime.now with datetime.utcnow, it breaks without freezegun

**Comment by spulec** [comment] 2019-09-24 23:24
Okay. I am going to close this in favor of https://github.com/spulec/freezegun/issues/89 then. As noted there, there are some backward-incompatibilities we would have to make to proceed.

**Closed by spulec** 2019-09-24 23:24 UTC
Labels: debugging
