### ISSUE TITLE
`freeze_time` could accept a timezone argument

### ISSUE THREAD

**Issue by charlax** [spulec/freezegun#87] opened 2015-03-05 22:49 UTC
What do you think of having `freeze_time` accept a timezone argument:

```python
@freeze_time('2015-03-09 09:00:00', timezone='US/Pacific')
```

That would require adding pytz to the requirements, which should be fine since most Python projects have it.

Thoughts? I might develop it.

**Comment by spulec** [comment] 2015-03-05 23:46
Not sure if you know this, but `freeze_time` already accepts a `tz_offset` argument.

If your suggestion was just to make it cleaner so that we could pass in 'nice' timezone names, then I could get behind that.

**Comment by charlax** [comment] 2015-03-05 23:54
Yes, I've seen `tz_offset`. The problem is that (1) it requires explicit knowledge about the offset (2) the offset changes depending on the datetime.

**Comment by spulec** [comment] 2015-03-05 23:57
Ah, right. I had forgotten about your second point. PR welcome.

**Comment by adamchainz** [comment] 2015-07-23 14:18
You don't need to put `pytz` in the requirements, it can be optional (`try: import; except ImportError: pytz = None` pattern) and then only used if `timezone` is passed.

**Comment by shreevatsar** [comment] 2015-08-18 15:56
Just FYI: one can already pass `freeze_time` a timezone-aware datetime object:

```
d = datetime(2015, 8, 18, 8, 51, 50, tzinfo=pytz.timezone('America/Los_Angeles'))
with freeze_time(d):
    print datetime.now()
```

(prints `2015-08-18 08:51:50-08:00`)

**Comment by agriffis** [comment] 2016-01-04 13:23
AFAIK you can also pass a timezone in the string, right?
```python
with freeze_time("2015-03-09 09:00:00 PST")
```

**Comment by agriffis** [comment] 2016-01-05 00:02
Regarding my previous comment, it turns out that dateutil's parser returns an aware datetime IFF the timezone in the string matches the default timezone of the host. In all other cases, dateutil's parser ignores the given timezone and returns a naive (and unadjusted) datetime.

```
>>> parse("12:00 EST")
datetime.datetime(2016, 1, 4, 12, 0, tzinfo=tzlocal())
>>> parse("12:00 CST")
datetime.datetime(2016, 1, 4, 12, 0)
>>> parse("12:00 MST")
datetime.datetime(2016, 1, 4, 12, 0)
```

Definitely fails the principle of least surprise for me, but there you have it.

**Comment by spulec** [comment] 2016-01-17 20:57
Going to close this with support for @shreevatsar 's solution

**Closed by spulec** 2016-01-17 20:57 UTC

**Comment by ze-phyr-us** [comment] 2016-01-18 04:56
@spulec That's a shame. While it works, it's a bit clumsy for an extremely common use case. (I, at least, have zero Python projects that can afford to ignore time zones.)

**Comment by spulec** [comment] 2016-01-18 16:22
Happy to accept a PR for it, but don't want to leave the issue open forever.

**Comment by jose-lpa** [comment] 2019-04-01 09:59
@shreevatsar solution does not work for me.

I might be doing something wrong, but definitely this is not very straightforward.

![Screenshot from 2019-04-01 10-59-04](https://user-images.githubusercontent.com/2226098/55319650-40fcf980-546d-11e9-8d86-f37ea1e769c7.png)

**Comment by fish-face** [comment] 2019-04-02 00:10
I am also not getting the described behaviour:

```
In [4]: dt = datetime(2018,1,1,tzinfo=pytz.timezone('America/Los_Angeles'))
In [6]: with freeze_time(dt): 
   ...:     print(datetime.now()) 
   ...:                                                                                    
2018-01-01 07:53:00
```
Ignoring the whacky time (this is caused by most timezones not being suitable for use as the `tzinfo` parameter) this is not even an aware datetime as @shreevatsar said (maybe this is a regression?)

**Comment by spumer** [comment] 2019-05-03 12:03
I got same problem with freezing time in Django tests =/

**Comment by IaroslavR** [comment] 2019-05-22 14:13
i can confirm problem mentioned by @spumer @fish-face and @jose-lpa  
my workaround:
```python
from datetime import datetime

import arrow
from freezegun import freeze_time

d = datetime(2015, 8, 18, 8, 51, 50, tzinfo=arrow.now("America/Los_Angeles").tzinfo)
with freeze_time(d):
    print datetime.now()
```
`2015-08-18 15:51:50`

**Comment by pngnviko** [comment] 2019-10-21 16:20
@spulec for me @shreevatsar 's solution doesn't work as well

**Comment by robertpro** [comment] 2020-09-03 02:49
This worked for me (I already had a helper function for tests)

```python
from datetime import datetime

from django.utils.timezone import get_current_timezone


def to_datetime(str_date: str, time: bool = False) -> datetime:
    str_format = "%Y-%m-%d"
    if time:
        str_format += "-%H:%M:%S"

    return datetime.strptime(str_date, str_format).astimezone(get_current_timezone())
```

On the tests:

```python
with freeze_time(to_datetime("2020-01-12")):
    ...
```

**Comment by spumer** [comment] 2020-09-03 06:54
Be ware when work with aware datetimes: https://github.com/spulec/freezegun/issues/348

**Comment by realmhamdy** [comment] 2022-01-26 04:26
Is there any technical reason why you're `convert_to_timezone_naive()` before setting the time? Is this absolutely needed?

**Comment by benthorner** [comment] 2022-04-26 07:22
@spumer @realmhamdy thanks for pointing to that issue - very helpful!
